# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 16:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='especialidades',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
