# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 14:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to=b'')),
                ('fechaRegistro', models.DateField(blank=True, default=datetime.date.today)),
                ('karma', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rango', models.CharField(choices=[('N', 'Novato'), ('E', 'Estudiante'), ('B', 'Becario'), ('P', 'Pelota')], max_length=1)),
                ('cuentaGmail', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Tiene que ser una cuenta de Google', regex='(^[a-zA-Z0-9_.+-]+@gmail.com+$)')])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Perfil')),
                ('creditos', models.IntegerField(blank=True, default=0)),
                ('notaMedia', models.FloatField(blank=True, null=True)),
                ('curso', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto')], max_length=1)),
                ('especialidad', models.CharField(blank=True, max_length=50)),
            ],
            bases=('usuarios.perfil',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Perfil')),
                ('despacho', models.IntegerField(blank=True, default=0)),
            ],
            bases=('usuarios.perfil',),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL),
        ),
    ]
