# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rango',
            field=models.CharField(choices=[('N', 'Novato'), ('E', 'Estudiante'), ('B', 'Becario'), ('P', 'Pelota')], default='Estudiante', max_length=1),
        ),
    ]
